"""Ingest MSMA Bot commands into Jarvis semantic memory."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from dotenv import load_dotenv
load_dotenv('config/.env')
from core.memory import JarvisMemory
from datetime import datetime

MSMA_COMMANDS = [
    ('ack_briefing', 'Acknowledge morning briefing'),
    ('actions', 'List pending actions'),
    ('add_contact', 'Add new customer contact'),
    ('add_document', 'Add document to knowledge base'),
    ('add_inventory', 'Add inventory item'),
    ('add_note', 'Add note to customer record'),
    ('add_prospect', 'Add new prospect/lead'),
    ('add_vendor', 'Add new supplier/vendor'),
    ('agent_log', 'View agent activity log'),
    ('agent_pause', 'Pause autonomous agent'),
    ('agent_resume', 'Resume autonomous agent'),
    ('agent_trust', 'Set agent trust level'),
    ('algo_stats', 'Algorithm performance statistics'),
    ('at_risk', 'Show at-risk customers'),
    ('at_risk_customers', 'Detailed at-risk customer analysis'),
    ('attribution', 'Revenue attribution report'),
    ('audit_log', 'View audit/activity log'),
    ('autonomy_settings', 'Configure bot autonomy level'),
    ('backup_now', 'Trigger immediate backup'),
    ('best_supplier_for', 'Find best supplier for a product'),
    ('block', 'Block email/contact'),
    ('brands', 'View tracked brand performance'),
    ('brief', 'Short morning briefing'),
    ('briefing', 'Full daily morning briefing with insights'),
    ('bulk_price', 'Bulk product price lookup'),
    ('cache_stats', 'Cache performance statistics'),
    ('campaign', 'Manage marketing campaigns'),
    ('carrier_performance', 'Carrier/delivery performance report'),
    ('cash_flow', 'Cash flow statement'),
    ('cash_forecast', 'Cash flow forecast'),
    ('certs', 'Manage certifications'),
    ('check_replies', 'Check email replies'),
    ('classify_customers', 'AI customer segmentation'),
    ('clean_drafts', 'Clean up draft emails'),
    ('clear_cache', 'Clear LLM/price cache'),
    ('clear_outage', 'Mark outage as resolved'),
    ('client_readiness', 'Client readiness score'),
    ('coach', 'AI sales coaching tips'),
    ('competitor_check', 'Check competitor pricing'),
    ('competitor_scrape', 'Scrape competitor website'),
    ('complete_milestone', 'Mark project milestone complete'),
    ('costs', 'View cost breakdown'),
    ('counterfactual', 'What-if scenario analysis'),
    ('crawl_status', 'Web crawler status'),
    ('create_po', 'Create purchase order'),
    ('create_shipment', 'Create shipment record'),
    ('credit_check', 'Customer credit check'),
    ('customer', 'Customer profile lookup'),
    ('customer_360', '360-degree customer view'),
    ('customer_groups', 'Customer segmentation groups'),
    ('customer_health', 'Customer health score'),
    ('customer_history', 'Full customer interaction history'),
    ('customer_lookup', 'Quick customer lookup'),
    ('dashboard', 'Full business dashboard'),
    ('deck', 'Generate presentation deck'),
    ('delete_model', 'Delete trained model'),
    ('deliverability', 'Email deliverability report'),
    ('delivery_costs', 'Delivery cost analysis'),
    ('delprice', 'Delete verified price entry'),
    ('demand', 'Demand analysis'),
    ('demand_forecast', 'Demand forecasting'),
    ('discoveries', 'AI market discoveries'),
    ('dlq', 'View dead letter queue (failed emails)'),
    ('dlq_retry', 'Retry failed email by ID'),
    ('documents', 'List documents'),
    ('draft', 'View/edit email draft'),
    ('email_summary', 'Summarize recent emails'),
    ('enroll_loyalty', 'Enroll customer in loyalty program'),
    ('finance', 'Finance overview'),
    ('finance_dashboard', 'Full financial dashboard'),
    ('find_leads', 'AI lead generation'),
    ('followup_queue', 'View followup queue'),
    ('followups', 'List pending followups'),
    ('forget', 'Delete memory/fact'),
    ('generate_invoice', 'Generate ZATCA-compliant invoice'),
    ('graph_customer', 'Customer knowledge graph'),
    ('graph_facts', 'View knowledge graph facts'),
    ('graph_search', 'Search knowledge graph'),
    ('graph_stats', 'Knowledge graph statistics'),
    ('graph_timeline', 'Customer timeline from graph'),
    ('heal_now', 'Trigger self-healing'),
    ('health', 'Quick health check'),
    ('health_full', 'Full system health check (DB, DLQ, PDPL, spend, disk)'),
    ('help', 'List all commands'),
    ('iktva', 'IKTVA compliance check'),
    ('image', 'Process image with AI'),
    ('image_status', 'Image processing queue status'),
    ('inbox_status', 'Email inbox status'),
    ('industry_news', 'Industry news digest'),
    ('insights', 'AI insights from data'),
    ('ios_setup', 'iOS shortcut setup guide'),
    ('jarvis_history', 'MSMA-Jarvis conversation history'),
    ('jarvis_improvements', 'Jarvis improvement suggestions'),
    ('jarvis_new_session', 'Start new Jarvis session'),
    ('jarvis_off', 'Disable Jarvis integration in MSMA'),
    ('jarvis_on', 'Enable Jarvis integration in MSMA'),
    ('jarvis_start', 'Start Jarvis bridge session'),
    ('jarvis_status', 'Jarvis integration status in MSMA'),
    ('jarvis_stop', 'Stop Jarvis bridge session'),
    ('jarvis_tools', 'List Jarvis tools available'),
    ('journal', 'View/add business journal entry'),
    ('knowledge_stats', 'Knowledge base statistics'),
    ('local_llm_status', 'Local LLM (Ollama) status'),
    ('log_contact', 'Log customer contact: /log_contact <platform> <type> <notes>'),
    ('lost_analysis', 'Win/loss analysis by customer'),
    ('low_stock', 'Low stock alerts'),
    ('market_intel', 'Market intelligence digest'),
    ('meeting', 'Log meeting notes'),
    ('mega_deal', 'Mega deal tracking'),
    ('mega_projects', 'Large project pipeline'),
    ('memory_stats', 'Bot memory/DB statistics'),
    ('metrics', 'Performance metrics'),
    ('mobile_url', 'Get mobile access URL'),
    ('model_routing', 'LLM model routing status'),
    ('morning', 'Short morning command alias'),
    ('morning_brief', 'Morning brief (alias)'),
    ('morning_brief_voice', 'Voice morning brief via Jarvis'),
    ('my_customers', 'Your customer list'),
    ('negotiate_email', 'AI-generated negotiation email'),
    ('note', 'Quick note'),
    ('notes', 'View all notes'),
    ('obsidian_status', 'Obsidian sync status'),
    ('obsidian_sync', 'Sync to Obsidian'),
    ('opens', 'View open quotes'),
    ('opportunity', 'Opportunity analysis'),
    ('outcome', 'Record quote outcome: /outcome <qnum> won|lost|no_response'),
    ('patterns', 'AI-detected business patterns'),
    ('payables', 'Accounts payable'),
    ('pcoc_check', 'PCOC compliance check'),
    ('pdf_rfqs', 'Process PDF RFQ attachments'),
    ('pdpl_audit', 'PDPL data privacy audit'),
    ('pending_deliveries', 'Pending delivery tracking'),
    ('pending_drafts', 'View pending email drafts'),
    ('pending_review', 'Items pending review'),
    ('perf', 'Performance summary'),
    ('performance', 'Full performance report'),
    ('pilot_outreach', 'Pilot customer outreach campaign'),
    ('pipeline_report', 'Sales pipeline report'),
    ('pl_statement', 'P&L statement'),
    ('portal_stats', 'Customer portal statistics'),
    ('portal_status', 'Customer portal status'),
    ('portals', 'List customer portals'),
    ('predict_quote_outcome', 'AI quote win probability prediction'),
    ('predict_revenue', 'Revenue prediction'),
    ('predict_stats', 'Prediction model statistics'),
    ('predictions_today', 'Today AI predictions'),
    ('prep_call', 'Prep for customer call'),
    ('preview_drafts', 'Preview email drafts'),
    ('preview_template', 'Preview email template'),
    ('price_strategy', 'Pricing strategy recommendation'),
    ('pricecheck', 'Check product price'),
    ('privacy', 'Privacy settings'),
    ('privacy_mode', 'Enable/disable privacy mode'),
    ('process_doc', 'Process document with AI'),
    ('product_info', 'Product information lookup'),
    ('profit_report', 'Profit report by customer/product'),
    ('project_create', 'Create new project'),
    ('project_dashboard', 'Project management dashboard'),
    ('project_status', 'Project status update'),
    ('promote_discovery', 'Promote AI discovery to knowledge base'),
    ('pull_model', 'Pull Ollama model'),
    ('quick_stats', 'Quick business stats'),
    ('quote_pdf', 'Generate quote PDF'),
    ('reactivation_run', 'Run customer reactivation campaign'),
    ('reactivation_stats', 'Reactivation campaign stats'),
    ('rebuild_kb', 'Rebuild knowledge base'),
    ('recall', 'Recall from bot memory'),
    ('receivables', 'Accounts receivable'),
    ('receive_po', 'Record received purchase order'),
    ('recent_intel', 'Recent market intelligence'),
    ('reorder_alerts', 'Inventory reorder alerts'),
    ('reports', 'Reports menu'),
    ('reprocess', 'Reprocess email/RFQ'),
    ('research_company', 'AI company research'),
    ('research_competitor', 'AI competitor research'),
    ('resilience', 'System resilience report'),
    ('resilience_status', 'Resilience module status'),
    ('restore_list', 'Restore deleted records'),
    ('resubmit_failed', 'Resubmit failed ZATCA invoice'),
    ('risk_report', 'Business risk report'),
    ('sales_report', 'Sales performance report'),
    ('save_campaign', 'Save campaign settings'),
    ('save_draft', 'Save email draft'),
    ('save_drafts_all', 'Save all pending drafts'),
    ('schedulers', 'View background scheduler status'),
    ('search', 'Search knowledge base'),
    ('security_check', 'Security audit'),
    ('seedprices', 'Seed product price database'),
    ('self_heal_status', 'Self-healing module status'),
    ('send_followup', 'Send followup email'),
    ('send_whatsapp', 'Send WhatsApp message'),
    ('signal_patterns', 'Customer signal patterns'),
    ('signal_status', 'Signal detection status'),
    ('similar_quotes', 'Find similar past quotes'),
    ('simulate_outage', 'Simulate system outage (test)'),
    ('smart_price', 'Smart price recommendation'),
    ('smart_quote_v2', 'Generate AI-powered quote (v2)'),
    ('soe_news', 'Saudi Arabia SOE news'),
    ('soe_scrape', 'Scrape SOE announcements'),
    ('spend', 'AI API spend/cost report'),
    ('sq', 'Alias for smart_quote_v2'),
    ('start', 'Start/intro message'),
    ('stats', 'Business statistics summary'),
    ('stock', 'Inventory stock levels'),
    ('supplier_compare', 'Compare supplier prices'),
    ('supplier_negotiate', 'Supplier negotiation assistant'),
    ('supplier_perf', 'Supplier performance report'),
    ('supplier_score', 'Supplier scoring'),
    ('suppliers', 'List suppliers'),
    ('tasks', 'View pending tasks'),
    ('tax_calendar', 'Tax due dates calendar'),
    ('tax_due', 'Tax payments due'),
    ('tax_report', 'Tax summary report'),
    ('tender_detail', 'Tender/RFP details'),
    ('tender_score', 'AI tender scoring'),
    ('tender_top', 'Top tender opportunities'),
    ('tenders', 'List active tenders'),
    ('tenders_scrape', 'Scrape tender portals'),
    ('test_local', 'Test local LLM'),
    ('testquote', 'Test quote generation'),
    ('tier', 'Customer tier management'),
    ('today', 'Today summary'),
    ('track', 'Track shipment'),
    ('track_competitor', 'Track competitor activity'),
    ('train_predictor', 'Train ML prediction model'),
    ('tune_promote', 'Promote tuning suggestion'),
    ('tune_status', 'Model tuning status'),
    ('upcoming_milestones', 'Upcoming project milestones'),
    ('update_document', 'Update document'),
    ('update_shipment', 'Update shipment status'),
    ('upsell_opportunities', 'AI upsell opportunities'),
    ('vacuum', 'Database vacuum/optimize'),
    ('validate_drafts', 'Validate email drafts'),
    ('vat_summary', 'VAT summary report'),
    ('vendor_notes', 'Vendor notes'),
    ('vendor_status', 'Vendor status'),
    ('vendor_timeline', 'Vendor activity timeline'),
    ('vendor_update', 'Update vendor information'),
    ('verifiedprices', 'View verified product prices database'),
    ('verify', 'Verify email/contact'),
    ('verify_email', 'Verify email address validity'),
    ('vip', 'VIP customer management'),
    ('vip_dashboard', 'VIP customer dashboard'),
    ('voice_commands', 'List voice commands'),
    ('voice_off', 'Disable voice/Jarvis replies in MSMA'),
    ('voice_on', 'Enable voice/Jarvis replies in MSMA'),
    ('voice_quote', 'Voice-activated quote generation'),
    ('voice_settings', 'Voice/TTS settings'),
    ('voice_test', 'Test voice output'),
    ('wa_test', 'Test WhatsApp integration'),
    ('watchdog_status', 'Watchdog service status'),
    ('wave_2_discover', 'Wave 2 customer discovery'),
    ('wave_2_status', 'Wave 2 campaign status'),
    ('weekly_actions', 'Weekly recommended actions (Saturday routine)'),
    ('weekly_report', 'Weekly business report'),
    ('whatsapp_messages', 'View recent WhatsApp messages'),
    ('whatsapp_status', 'WhatsApp integration status'),
    ('whatsapp_templates', 'WhatsApp message templates'),
    ('whoknows', 'Who knows about this customer/product'),
    ('win_rate', 'Win rate analysis'),
    ('win_tracker', 'Track recent wins'),
    ('zakat_calc', 'Zakat calculation'),
    ('zatca_check', 'ZATCA compliance check'),
    ('zatca_compliance', 'ZATCA full compliance report'),
    ('zatca_guide', 'ZATCA e-invoicing guide'),
    ('zatca_status', 'ZATCA integration status'),
]

m = JarvisMemory()
cur = m.conn.cursor()
cur.execute("DELETE FROM semantic WHERE category='msma_commands'")
for cmd, desc in MSMA_COMMANDS:
    cur.execute(
        'INSERT OR REPLACE INTO semantic (key, value, category, updated_at) VALUES (?, ?, ?, ?)',
        (f'msma_cmd_{cmd}', f'/{cmd}: {desc}', 'msma_commands', datetime.now().isoformat())
    )
m.conn.commit()
count = cur.execute("SELECT COUNT(*) FROM semantic WHERE category='msma_commands'").fetchone()[0]
print(f'Ingested {count} MSMA commands into Jarvis memory')
# Show sample
for row in cur.execute("SELECT value FROM semantic WHERE category='msma_commands' ORDER BY key LIMIT 8").fetchall():
    print(f'  {row[0]}')
